# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(222, 270)
        self.generate_btn = QtWidgets.QPushButton(Dialog)
        self.generate_btn.setGeometry(QtCore.QRect(30, 170, 161, 23))
        self.generate_btn.setObjectName("generate_btn")
        self.contents_lbl = QtWidgets.QLabel(Dialog)
        self.contents_lbl.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.contents_lbl.setObjectName("contents_lbl")
        self.picture_lbl = QtWidgets.QLabel(Dialog)
        self.picture_lbl.setGeometry(QtCore.QRect(30, 120, 150, 16))
        self.picture_lbl.setObjectName("picture_lbl")
        self.picture_select_btn = QtWidgets.QPushButton(Dialog)
        self.picture_select_btn.setGeometry(QtCore.QRect(160, 140, 31, 23))
        self.picture_select_btn.setObjectName("picture_select_btn")
        self.contents_txt_box = QtWidgets.QLineEdit(Dialog)
        self.contents_txt_box.setGeometry(QtCore.QRect(30, 90, 161, 20))
        self.contents_txt_box.setObjectName("contents_txt_box")
        self.picture_txt_box = QtWidgets.QLineEdit(Dialog)
        self.picture_txt_box.setGeometry(QtCore.QRect(30, 140, 121, 20))
        self.picture_txt_box.setObjectName("picture_txt_box")
        self.about_btn = QtWidgets.QPushButton(Dialog)
        self.about_btn.setGeometry(QtCore.QRect(30, 230, 161, 23))
        self.about_btn.setObjectName("about_btn")
        self.help_btn = QtWidgets.QPushButton(Dialog)
        self.help_btn.setGeometry(QtCore.QRect(30, 200, 161, 23))
        self.help_btn.setObjectName("help_btn")
        self.title_lbl = QtWidgets.QLabel(Dialog)
        self.title_lbl.setGeometry(QtCore.QRect(70, 30, 115, 16))
        self.title_lbl.setObjectName("title_lbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.generate_btn.setText(_translate("Dialog", "Generar"))
        self.contents_lbl.setText(_translate("Dialog", "Texto o URL"))
        self.picture_lbl.setText(_translate("Dialog", "Foto para QR (Opcional)"))
        self.picture_select_btn.setText(_translate("Dialog", "..."))
        self.about_btn.setText(_translate("Dialog", "About"))
        self.help_btn.setText(_translate("Dialog", "Como usar"))
        self.title_lbl.setText(_translate("Dialog", "Generador de QR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
